### PR TITLE
fix: use of webpack as a global dependency.

### PR DESCRIPTION
**Pull request by osnoser1**
* Not tested on linux, only windows.

### CODE REVIEW

**Comment by dolanmiu** [comment]
Thanks!

**Comment by dolanmiu** [comment]
@osnoser1 is this an actual issue? I do not have `webpack` installed globally, and it works for me just fine previously

**Comment by osnoser1** [comment]
Yes, I had to install globally to make it work. 😕
I also had to add to the `packages.json` `@ngtools/webpack` for: https://github.com/angular/angular-cli/issues/6845. This was some time ago, I have not tried removing it again and try it.
And it is not documented that it is necessary to install `awesome-typescript-loader`, I do not know if it will be correct, or there will be a way to add it as it depends on` ng-cli-electron` and make it be used with `webpack`.

**Comment by dolanmiu** [comment]
It should pop up as a `WARNING` when you install:

https://github.com/dolanmiu/ng-cli-electron/blob/master/package.json#L47

`awesome-typescript-loader` is a peerDependency

I didn't think it was nessesary to write it down cos it should be clear I think

**Comment by dolanmiu** [comment]
Released v1.2.2

https://github.com/dolanmiu/ng-cli-electron/releases/tag/1.2.2

**Pull request merged**
